### ISSUE TITLE
Error while performing 'terraform plan' for example 'user-data'

### ISSUE THREAD

**Issue by Nols1000** [thojkooi/terraform-digitalocean-docker-swarm-mode#10] opened 2018-01-08 02:03 UTC
````bash
Error: Error running plan: 2 error(s) occurred:

* module.swarm-cluster.module.managers.output.manager_token: Resource 'data.external.swarm_tokens' does not have attribute 'result.manager' for variable 'data.external.swarm_tokens.result.manager'
* module.swarm-cluster.module.managers.output.worker_token: Resource 'data.external.swarm_tokens' does not have attribute 'result.worker' for variable 'data.external.swarm_tokens.result.worker'
````
Seems this is related hashicorp/terraform#16728

**Comment by thojkooi** [comment] 2018-01-08 20:47
Thanks @Nols1000 , I will look into it.

**Comment by thojkooi** [comment] 2018-01-21 13:18
This is now fixed with thojkooi/terraform-digitalocean-swarm-managers#6 merged. 

```
[user-data] $ terraform get -update=true
[user-data] $ terraform plan

....

Plan: 6 to add, 0 to change, 0 to destroy.
```
Works again as intended. 

Thanks for letting me know @Nols1000

**Closed as completed by thojkooi** 2018-01-21 13:18 UTC
Labels: bug
